import React,{useState,useEffect} from 'react'
import axios from 'axios'
import Image from 'next/image'
import Head from 'next/head'
import {BsSearch} from 'react-icons/bs'
import Weather from '@/components/Weather'
import Spinner from '@/components/Spinner'


export default function Home() {
  
   
   const [city,setCity] = useState('')
   const [loading,setLoading] = useState(false)
   const [weather,setWeather] = useState({})
   const url = `http://api.weatherapi.com/v1/current.json?key=e07d43ede590499abfc230252230907&q=${city}`

   const handleSubmit = (e) =>{
           e.preventDefault()
           setLoading(true)
           axios.get(url)
           .then((response) => {
            setWeather(response.data)
            console.log(response.data);
            setCity('')
            setLoading(false)
           } )
    }

   if (loading) {
     return <Spinner/>
   }else{

  return (
    <section>
        <Head>
          <title>weather-app</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="favicon.ico"/>
        </Head>
        <div className='w-full h-screen'>
               <Image 
                   src={'https://images.unsplash.com/photo-1510784722466-f2aa9c52fff6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80'} 
                   alt='/' 
                   layout='fill' 
                   objectFit='cover'
                   className='relative z-0'
               />
               <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-100'>
                    <div className='w-full flex justify-center items-center py-12'>    
                        <form  className='flex justify-between items-center h-20 max-w-[400px] bg-transparent rounded-xl border-2 border-gray-400 p-3'>
                             <div className='flex items-center justify-center'>
                                 <input onChange={(e)=> {setCity(e.target.value)}} type='text' placeholder='Search for city' className='focus:outline-none bg-transparent text-2xl text-white'/>
                             </div>
                             <button onClick={handleSubmit} className='text-gray-300'>
                                 <BsSearch size={30}/>
                             </button>
                        </form>
                    </div>
                    {weather && <Weather data={weather}/>}
                    
                </div>
               
        </div>
        
    </section>
  )}
}
